// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOTdzSYTLF-w7onx_clXRu7NG3NfAGc5g',
    appId: '1:733868478320:web:27948e9810f0aac965c9b5',
    messagingSenderId: '733868478320',
    projectId: 'whatsapp-backend-67dfb',
    authDomain: 'whatsapp-backend-67dfb.firebaseapp.com',
    storageBucket: 'whatsapp-backend-67dfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRbXpN0AB3c6LY7IdN829NsSpqo-DNuo',
    appId: '1:733868478320:android:26dd6cf6d5b5d7c265c9b5',
    messagingSenderId: '733868478320',
    projectId: 'whatsapp-backend-67dfb',
    storageBucket: 'whatsapp-backend-67dfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJG9xMoF1eku8xFqTtZ_37OctIy7F_i6A',
    appId: '1:733868478320:ios:b96afb0da08a31ce65c9b5',
    messagingSenderId: '733868478320',
    projectId: 'whatsapp-backend-67dfb',
    storageBucket: 'whatsapp-backend-67dfb.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJG9xMoF1eku8xFqTtZ_37OctIy7F_i6A',
    appId: '1:733868478320:ios:b96afb0da08a31ce65c9b5',
    messagingSenderId: '733868478320',
    projectId: 'whatsapp-backend-67dfb',
    storageBucket: 'whatsapp-backend-67dfb.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOTdzSYTLF-w7onx_clXRu7NG3NfAGc5g',
    appId: '1:733868478320:web:11c12cb19eb84c7f65c9b5',
    messagingSenderId: '733868478320',
    projectId: 'whatsapp-backend-67dfb',
    authDomain: 'whatsapp-backend-67dfb.firebaseapp.com',
    storageBucket: 'whatsapp-backend-67dfb.firebasestorage.app',
  );
}
